train:
    params:
        batch_size: 64
        epoch: 80
        lr: 0.001
        decay: 0.5
        decay_step: 60
        warmup: 5

    save:
        metapath: "./output/exp/GazeDPTR"
        folder: iv
        model_name: trans6
        step: 10

    data:
        origin:
            image: "./dataset/IVGazeDataset/Origin"
            label: "./dataset/IVGazeDataset/Origin/label_class"
            header: True
            name: ivorigin
            isFolder: True
        norm:
            image: "./dataset/IVGazeDataset/Norm"
            label: "./dataset/IVGazeDataset/Norm/label_class"
            header: True
            name: ivnorm
            isFolder: True
    
            
    pretrain:
        enable: False
        path: None
        device: 0

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512
